"""
Configuration constants for UnicodeHexMono font generation.

This module contains all configuration parameters for font generation, organized into sections:
- Font metadata (name, version, copyright)
- Font metrics (EM size, ascent, descent)
- Glyph design parameters (box size, stroke width, corner radius)
- Hex digit display parameters (digit size, grid spacing)
- Glyph positioning constants
- Unicode ranges and validation
- Multi-file generation settings
"""

# ============================================================================
# Configuration
# ============================================================================


FONT_NAME = "UnicodeHexMono"
FONT_FAMILY = "UnicodeHexMono"
FONT_STYLE = "Regular"
FONT_FULLNAME = "UnicodeHexMono Regular"
FONT_VERSION = "1.0"
FONT_COPYRIGHT = "Generated by FontForge script"

# Font metrics
EM_SIZE = 1000
ASCENT = 800
DESCENT = 200

# Glyph design parameters
GLYPH_WIDTH = EM_SIZE  # Monospaced: all glyphs same width
BOX_SIZE = 700  # Square box size
BOX_MARGIN = (EM_SIZE - BOX_SIZE) // 2  # Center the box horizontally
BOX_STROKE_WIDTH = 40
CORNER_RADIUS = 70  # Rounded corner radius for BMP and Supplementary Planes 1-15
CORNER_RADIUS_PLANE16 = 120  # More rounded corners for Plane 16 (U+100000-U+10FFFD)

# Hex digit display parameters (for U+0000 to U+FFFF)
DIGIT_SIZE = 260          # Size of each hex digit (increased from 190, 37% larger for better visibility)
GRID_SPACING = 30         # Spacing between digits in grid (increased from 20)
DIGIT_STROKE_WIDTH = 25   # Stroke width for digit paths

# 2-digit hex display (for U+0000 to U+00FF - ASCII & Extended ASCII)
TWO_DIGIT_SIZE = 400      # Huge size for 2-digit display (54% larger than standard DIGIT_SIZE)

# Glyph positioning
GLYPH_Y_OFFSET = -50      # Vertical offset for centering glyphs

# U+FFFD replacement character display
REPLACEMENT_CHAR_PADDING = 100  # Padding around the X symbol

# Supplementary planes (U+10000 to U+FFFFF) 5-digit split layout
PLANE_DIGIT_SIZE = 290           # Size of the plane digit (larger than standard)
PLANE_SECTION_SPACING = 50       # Spacing between plane digit and 2x2 grid
SUPPLEMENTARY_GRID_SPACING = 40  # Grid spacing for 2x2 grid in supplementary planes

# Unicode ranges
UNICODE_MIN = 0x0000
UNICODE_MAX = 0x10FFFD

# Surrogate range to skip (invalid codepoints)
SURROGATE_START = 0xD800
SURROGATE_END = 0xDFFF

# Multi-file configuration: Split Unicode into manageable chunks
# Each chunk stays well under the 65,535 glyph limit
GLYPHS_PER_FILE = 60000  # Conservative limit (allows room for .notdef, etc.)

# Output format
OUTPUT_FORMAT = 'otf'  # Only OTF, no TTF support
